add snowflake terraform workflow

diff --git a/.github/workflows/tf-dev.yml b/.github/workflows/tf-dev.yml
--- a/.github/workflows/tf-dev.yml
+++ b/.github/workflows/tf-dev.yml
@@ -14,10 +14,17 @@ on:
       - 'environments/dev/**'
       - 'modules/**'
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: false
+
 env:
   AWS_REGION: "ap-northeast-1"
-  TF_WORKING_DIR: "./environments/dev"
   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
+
+  # Snowflake
+  TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
+  TF_VAR_snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
 
 permissions:
   id-token: write
@@ -32,11 +39,17 @@ jobs:
 
     defaults:
       run:
-        working-directory: ${{ env.TF_WORKING_DIR }}
+        working-directory: environments/${{ github.base_ref || github.ref_name }}
 
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
+
+      - name: Check if source branch is stg
+        if: github.base_ref == 'release' && github.head_ref != 'main'
+        run: |
+          echo "Error: Pull Requests to 'release' must come from 'main' branch."
+          exit 1
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -51,11 +64,11 @@ jobs:
 
       - name: Terraform Init
         id: init
-        run: terraform init
+        run: terraform init -upgrade -no-color
 
       - name: Terraform Format
         id: fmt
-        run: terraform fmt -check
+        run: terraform fmt -check -recursive
 
       - name: Terraform Validate
         id: validate
@@ -64,7 +77,7 @@ jobs:
       - name: Terraform Plan
         id: plan
         if: github.event_name == 'pull_request'
-        run: terraform plan -no-color
+        run: terraform plan -no-color -input=false
         continue-on-error: true
 
       - name: Comment PR
@@ -94,5 +107,39 @@ jobs:
 
       - name: Terraform Apply
         if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
-        run: terraform apply -auto-approve
+        run: terraform apply -auto-approve -no-color
+
+      - name: Find Pull Request Number
+        if: github.event_name == 'push'
+        id: find_pr
+        uses: jwalton/gh-find-current-pr@v1
+        with:
+          state: closed
+
+      # add apply result comment to PR
+      - name: Post Apply Result to Pull Request
+        if: github.event_name == 'push' && steps.find_pr.outputs.number != ''
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const output = `#### Terraform Apply Result: \`${{ steps.apply.outcome }}\`
+
+            <details><summary>Show Apply Output</summary>
+
+            \`\`\`terraform
+            ${{ steps.apply.outputs.stdout }}
+            \`\`\`
+
+            </details>
+
+            *Action: \`terraform apply\` after merge by @${{ github.actor }}*`;
+
+            github.rest.issues.createComment({
+              issue_number: ${{ steps.find_pr.outputs.number }},
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
+
 
